[package]
name = "matchmaking"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
csv = "1"
docx-rs = { git = "https://github.com/ephraimkunz/docx-rs", branch = "ekunz-matchmaking-avoid-balanceSingleByteDoubleByteWidth" }
itertools = "0.15"
rand = "0.10"
regex = "1"
rustc-hash = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
open = "5"

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
getrandom = { version = "0.4", features = ["wasm_js"] }
serde = { version = "1", features = ["derive"] }
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"

[profile.release]
panic = "abort"
opt-level = "s"  # optimize for size
codegen-units = 1

[lib]
crate-type = ["cdylib", "rlib"]

